-- MySQL Script generated by MySQL Workbench
-- 04/02/17 22:01:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accounts` (
  `User_Name` VARCHAR(20) NOT NULL,
  `Active` BIT(20) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `User_Role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`User_Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `ID` VARCHAR(50) NOT NULL,
  `Amount` DOUBLE NOT NULL,
  `Customer_Address` VARCHAR(255) NOT NULL,
  `Customer_Email` VARCHAR(128) NOT NULL,
  `Customer_Name` VARCHAR(255) NOT NULL,
  `Customer_Phone` VARCHAR(128) NOT NULL,
  `Order_Date` DATETIME(20) NOT NULL,
  `Order_Num` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type_Tools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type_Tools` (
  `Type_ID` VARCHAR(50) NOT NULL,
  `TypeName` VARCHAR(150) NULL,
  PRIMARY KEY (`Type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `Model_ID` VARCHAR(50) NOT NULL,
  `Type_ID` VARCHAR(50) NOT NULL,
  `Model_Name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Model_ID`),
  INDEX `Type_ID_idx` (`Type_ID` ASC),
  CONSTRAINT `Type_ID`
    FOREIGN KEY (`Type_ID`)
    REFERENCES `mydb`.`Type_Tools` (`Type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tools` (
  `Tools_ID` VARCHAR(50) NOT NULL,
  `Model_ID` VARCHAR(50) NOT NULL,
  `Type_ID` VARCHAR(50) NOT NULL,
  `Cost` INT NOT NULL,
  `Length` INT NOT NULL,
  `Height` INT NOT NULL,
  `Weight` INT NOT NULL,
  `Power` INT NOT NULL,
  `Speed` INT NOT NULL,
  PRIMARY KEY (`Tools_ID`),
  INDEX `Model_ID_idx` (`Model_ID` ASC),
  INDEX `Type_ID_idx` (`Type_ID` ASC),
  CONSTRAINT `Model_ID`
    FOREIGN KEY (`Model_ID`)
    REFERENCES `mydb`.`Model` (`Model_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Type_ID`
    FOREIGN KEY (`Type_ID`)
    REFERENCES `mydb`.`Type_Tools` (`Type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_Details` (
  `ID` VARCHAR(50) NOT NULL,
  `Amount` DOUBLE NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Quanity` INT NOT NULL,
  `ORDER_ID` VARCHAR(50) NOT NULL,
  `Tools_ID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Order_ID_idx` (`ORDER_ID` ASC),
  INDEX `Tools_ID_idx` (`Tools_ID` ASC),
  CONSTRAINT `Order_ID`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `mydb`.`Orders` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tools_ID`
    FOREIGN KEY (`Tools_ID`)
    REFERENCES `mydb`.`Tools` (`Tools_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



